print("What kind of shoes do birds wear?")
input()
print("vel-crow!")
input()
print("why is the headless horseman headless?")
input()
print("he was a birdwatcher who made the mistake of joining the military.")
input()
print("he heard DUCK and said where?")
input()
print("which one weighs more: an ounce of gold or an ounce of feathers?")
input()
print("an ounce of gold!")
input()
print("the troy ounce, which is used for precious metals, weighs 10% more than the standard, aka avoirdupois, ounce.")
input()
print("okay that one was a very nerdy joke i'm done now.")