print("this is a text story")
name = input ("what's your name? ")
print("")
print("")
print("")
input("")
answer = input ("(206)351-1429 is an unfamiliar number. would you like to report spam and send to junk? ")
if answer == "yes":
    print("(206)351-1429 has been reported spam and has been blocked from sending you messages.")
else:
    print("(206)351-1429 has been renamed to: 'Maybe: Stacey Quinn'")
    print(f"ⓜ️: hey you're {name} right? ")
    input()
    print("ⓜ️: wait omg that sounds so creepy lemme try that again")
    print("ⓜ️: ok pretend i never said that")
    print("ⓜ️: or this.")
    print("ⓜ️: okay yeah so pretend i've never said anything to you.")
    print("")
    input()
    print(f"ⓜ️:hii {name} this is stacey we met last week at the park")
    input()
    print("ⓜ️:so like you know how like i told you abt like my parents n stuff")
    colleges = input ("ⓜ️:yh so like this is a weird question but what college did your parents go to? ")
    if colleges == "idk":
        print("ⓜ️: oh")
        input()
        print("ⓜ️: gimme a sec")
        input()
        print("ⓜ️: dude wait i asked my dads and they think ur parents might have gone to the same college as them")
    else:
        print("ⓜ️ :omg wait")
        print("...")
        print(f"ⓜ️ :dude my dads went to {colleges}!")
        print("ⓜ️ :like what are the chancesss")
        print("")
    input()
    print("")
    print("ⓜ️ :ohmygod WAIT.")
    input()
    print("ⓜ️ :i found their yearbook")
    input()
    pnames = input ("ⓜ️ :okay what's your parents' names again?")
    four = input (f"ⓜ️ :yoooo okay i'm looking thru the yearbook i'm looking for {pnames} right? ")
    if four == "no":
        five = input ("ⓜ️ :oh thats mb what were they then? ")
        print(f"ⓜ️ :ok so to clarify i'm looking for {five} not {pnames}")
        input()
        print("ⓜ️ :yeah yeah whatever")
    input()
    print("ⓜ️ :ok found em")
    input()
    print("ⓜ️ :they look goofy lmao")
    print("")
    input()
    print("ⓜ️ :i see where you get it from")
    input()
    print("ⓜ️ :my dad read my texts and he's making me apologize")
    input()
    print("ⓜ️ :sorry for calling you and your parents goofy i guess.")