print("this is a text story")
name = input ("what's your name?")
print("hii {name} this is stacy we met last week at the park")
input()
print("so like you know how like i told you about like my parents and stuff")
input()
print("turns out they know yours! ikr??")
input()
print("...")
print("so anyway yeah my dad went to highschool with them")
print("like what are the chances")
input()
print("and i found his yearbook")
pnames = input ("okay what's your parents' names again")
print("yoooo okay i'm looking thru the yearbook you said {pnames} right?")
input()
print("they look goofy i see where you get it from")